//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class arguments
    {
        public arguments()
        {
            this.comments = new HashSet<comments>();
            this.argumentvotes = new HashSet<argumentvotes>();
        }
    
        public int PK { get; set; }
        public int FKSparks { get; set; }
        public int FKAccounts { get; set; }
        public string strArgument { get; set; }
        public bool bIsAgree { get; set; }
        public Nullable<int> nFlagCount { get; set; }
        public string strConclusion { get; set; }
        public string strCitations { get; set; }
    
        public virtual accounts accounts { get; set; }
        public virtual sparks sparks { get; set; }
        public virtual ICollection<comments> comments { get; set; }
        public virtual ICollection<argumentvotes> argumentvotes { get; set; }
    }
}
