//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comments
    {
        public comments()
        {
            this.commentvotes = new HashSet<commentvotes>();
            this.comments1 = new HashSet<comments>();
            this.heat = new HashSet<heat>();
        }
    
        public int PK { get; set; }
        public int FKArguments { get; set; }
        public int FKAccounts { get; set; }
        public int FKParentComment { get; set; }
        public string strComment { get; set; }
    
        public virtual accounts accounts { get; set; }
        public virtual arguments arguments { get; set; }
        public virtual ICollection<commentvotes> commentvotes { get; set; }
        public virtual ICollection<comments> comments1 { get; set; }
        public virtual comments comments2 { get; set; }
        public virtual ICollection<heat> heat { get; set; }
    }
}
