//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class errorlog
    {
        public int PK { get; set; }
        public Nullable<int> FKAccounts { get; set; }
        public string strControllerView { get; set; }
        public string strMessage { get; set; }
        public string strMethod { get; set; }
        public string strStackTrace { get; set; }
        public string strVariableName { get; set; }
        public Nullable<System.DateTime> dDate { get; set; }
    
        public virtual accounts accounts { get; set; }
    }
}
