//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class heat
    {
        public int PK { get; set; }
        public int FKComments { get; set; }
        public int FKAccounts { get; set; }
        public bool bIsPositive { get; set; }
        public int nHeatAmount { get; set; }
    
        public virtual accounts accounts { get; set; }
        public virtual comments comments { get; set; }
    }
}
