//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class influencegains
    {
        public int PK { get; set; }
        public bool bIsPositive { get; set; }
        public int FKAccountsContributor { get; set; }
        public int FKAccountsReceived { get; set; }
        public int FKSubjectMatters { get; set; }
    
        public virtual accounts accounts { get; set; }
        public virtual accounts accounts1 { get; set; }
        public virtual subjectmatters subjectmatters { get; set; }
    }
}
