//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class interactionlog
    {
        public int PK { get; set; }
        public string strControllerView { get; set; }
        public System.DateTime dDate { get; set; }
        public int FKInteractionTypes { get; set; }
    
        public virtual interactiontypes interactiontypes { get; set; }
    }
}
