//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class profiles
    {
        public int PK { get; set; }
        public int FKAccounts { get; set; }
        public string strFirstName { get; set; }
        public string strMiddleName { get; set; }
        public string strLastName { get; set; }
        public string strProfilePicturePath { get; set; }
        public Nullable<System.DateTime> dDateOfBirth { get; set; }
        public Nullable<int> FKGenders { get; set; }
        public string strStatus { get; set; }
        public Nullable<int> FKReligions { get; set; }
        public Nullable<int> FKPoliticalIdeologies { get; set; }
        public Nullable<int> nIncome { get; set; }
        public Nullable<int> FKEducationLevels { get; set; }
        public Nullable<int> FKCities { get; set; }
    
        public virtual accounts accounts { get; set; }
        public virtual cities cities { get; set; }
        public virtual educationlevels educationlevels { get; set; }
        public virtual genders genders { get; set; }
        public virtual politicalideologies politicalideologies { get; set; }
        public virtual religions religions { get; set; }
    }
}
