//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sparkinterestvotes
    {
        public int PK { get; set; }
        public int FKSparks { get; set; }
        public bool bIsUpVote { get; set; }
        public int FKAccounts { get; set; }
    
        public virtual accounts accounts { get; set; }
        public virtual sparks sparks { get; set; }
    }
}
