//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Spark.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class sparkdbEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new sparkdbEntities object using the connection string found in the 'sparkdbEntities' section of the application configuration file.
        /// </summary>
        public sparkdbEntities() : base("name=sparkdbEntities", "sparkdbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new sparkdbEntities object.
        /// </summary>
        public sparkdbEntities(string connectionString) : base(connectionString, "sparkdbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new sparkdbEntities object.
        /// </summary>
        public sparkdbEntities(EntityConnection connection) : base(connection, "sparkdbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<accounts> accounts
        {
            get
            {
                if ((_accounts == null))
                {
                    _accounts = base.CreateObjectSet<accounts>("accounts");
                }
                return _accounts;
            }
        }
        private ObjectSet<accounts> _accounts;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the accounts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToaccounts(accounts accounts)
        {
            base.AddObject("accounts", accounts);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="sparkdbModel", Name="accounts")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class accounts : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new accounts object.
        /// </summary>
        /// <param name="pK">Initial value of the PK property.</param>
        /// <param name="strUserName">Initial value of the strUserName property.</param>
        /// <param name="strPassword">Initial value of the strPassword property.</param>
        /// <param name="bIsActivated">Initial value of the bIsActivated property.</param>
        /// <param name="strSalt">Initial value of the strSalt property.</param>
        public static accounts Createaccounts(global::System.Int32 pK, global::System.String strUserName, global::System.String strPassword, global::System.Boolean bIsActivated, global::System.String strSalt)
        {
            accounts accounts = new accounts();
            accounts.PK = pK;
            accounts.strUserName = strUserName;
            accounts.strPassword = strPassword;
            accounts.bIsActivated = bIsActivated;
            accounts.strSalt = strSalt;
            return accounts;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PK
        {
            get
            {
                return _PK;
            }
            set
            {
                if (_PK != value)
                {
                    OnPKChanging(value);
                    ReportPropertyChanging("PK");
                    _PK = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PK");
                    OnPKChanged();
                }
            }
        }
        private global::System.Int32 _PK;
        partial void OnPKChanging(global::System.Int32 value);
        partial void OnPKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String strUserName
        {
            get
            {
                return _strUserName;
            }
            set
            {
                OnstrUserNameChanging(value);
                ReportPropertyChanging("strUserName");
                _strUserName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("strUserName");
                OnstrUserNameChanged();
            }
        }
        private global::System.String _strUserName;
        partial void OnstrUserNameChanging(global::System.String value);
        partial void OnstrUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String strPassword
        {
            get
            {
                return _strPassword;
            }
            set
            {
                OnstrPasswordChanging(value);
                ReportPropertyChanging("strPassword");
                _strPassword = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("strPassword");
                OnstrPasswordChanged();
            }
        }
        private global::System.String _strPassword;
        partial void OnstrPasswordChanging(global::System.String value);
        partial void OnstrPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean bIsActivated
        {
            get
            {
                return _bIsActivated;
            }
            set
            {
                OnbIsActivatedChanging(value);
                ReportPropertyChanging("bIsActivated");
                _bIsActivated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("bIsActivated");
                OnbIsActivatedChanged();
            }
        }
        private global::System.Boolean _bIsActivated;
        partial void OnbIsActivatedChanging(global::System.Boolean value);
        partial void OnbIsActivatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String strSalt
        {
            get
            {
                return _strSalt;
            }
            set
            {
                OnstrSaltChanging(value);
                ReportPropertyChanging("strSalt");
                _strSalt = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("strSalt");
                OnstrSaltChanged();
            }
        }
        private global::System.String _strSalt;
        partial void OnstrSaltChanging(global::System.String value);
        partial void OnstrSaltChanged();

        #endregion

    
    }

    #endregion

    
}
