//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sparks
    {
        public sparks()
        {
            this.arguments = new HashSet<arguments>();
            this.sparkinterestvotes = new HashSet<sparkinterestvotes>();
            this.sparkscategories = new HashSet<sparkscategories>();
        }
    
        public int PK { get; set; }
        public int FKAccountsCreatedBy { get; set; }
        public int FKSubjectMatters { get; set; }
        public string strImagePath { get; set; }
        public string strTopic { get; set; }
        public string strDescription { get; set; }
        public Nullable<System.DateTime> dDateCreated { get; set; }
        public Nullable<System.DateTime> dDateModified { get; set; }
    
        public virtual accounts accounts { get; set; }
        public virtual ICollection<arguments> arguments { get; set; }
        public virtual ICollection<sparkinterestvotes> sparkinterestvotes { get; set; }
        public virtual ICollection<sparkscategories> sparkscategories { get; set; }
        public virtual subjectmatters subjectmatters { get; set; }
    }
}
