//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sparkscategories
    {
        public int PK { get; set; }
        public int FKSparks { get; set; }
        public int FKCategories1 { get; set; }
        public int FKCategories2 { get; set; }
        public int FKCategories3 { get; set; }
    
        public virtual sparks sparks { get; set; }
        public virtual tags tags { get; set; }
        public virtual tags tags1 { get; set; }
        public virtual tags tags2 { get; set; }
    }
}
