//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class subjectmatters
    {
        public subjectmatters()
        {
            this.influencegains = new HashSet<influencegains>();
            this.sparks = new HashSet<sparks>();
            this.subjectmatterspreads = new HashSet<subjectmatterspreads>();
            this.subjectmatterspreads1 = new HashSet<subjectmatterspreads>();
        }
    
        public int PK { get; set; }
        public string strName { get; set; }
    
        public virtual ICollection<influencegains> influencegains { get; set; }
        public virtual ICollection<sparks> sparks { get; set; }
        public virtual ICollection<subjectmatterspreads> subjectmatterspreads { get; set; }
        public virtual ICollection<subjectmatterspreads> subjectmatterspreads1 { get; set; }
    }
}
