//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class transactions
    {
        public int PK { get; set; }
        public int FKAccountsBuyer { get; set; }
        public int FKTransactionTypes { get; set; }
        public int nAmount { get; set; }
        public System.DateTime dDateCreated { get; set; }
        public System.DateTime dDateModified { get; set; }
        public int FKTransactionStates { get; set; }
    
        public virtual accounts accounts { get; set; }
        public virtual transactionstates transactionstates { get; set; }
        public virtual transactiontypes transactiontypes { get; set; }
    }
}
